unit = l | dl | cl | ml | km | m | dm | cm | mm | kg | hg | g | mg | ton | km2 | m2 | dm2 | cm2 | mm2 | hectare

(* Volume *)
l = #'(?i)l' | #'(?i)lit(er|re)s?'
dl = #'(?i)dls?' | #'(?i)decilit(er|re)s?'
cl = #'(?i)cls?' | #'(?i)centilit(er|re)s?'
ml = #'(?i)mls?' | #'(?i)millilit(er|re)s?'

(* Distance *)
km = #'(?i)km' | #'(?i)kilomet(er|re)s?'
m = #'(?i)m' | #'(?i)met(er|re)s?'
dm = #'(?i)dm' | #'(?i)decimet(er|re)s?'
cm = #'(?i)cm' | #'(?i)centimet(er|re)s?'
mm = #'(?i)mm' | #'(?i)millimet(er|re)s?'

(* Weight *)
kg = #'(?i)kg' | #'(?i)kilograms?'
hg = #'(?i)hg' | #'(?i)hectograms?'
g = #'(?i)g' | #'(?i)grams?'
mg = #'(?i)mg' | #'(?i)milligrams?'
ton = #'(?i)tons?' | #'(?i)tonnes?'

(* Area *)
km2 = square-prefix <' '> km | km square-suffix
m2 = square-prefix <' '> m | m square-suffix
dm2 = square-prefix <' '> dm | dm square-suffix
cm2 = square-prefix <' '> cm | cm square-suffix
mm2 = square-prefix <' '> mm | mm square-suffix
hectare = #'(?i)hectare' | #'(?i)ha'

(* Combined *)
<combined> = measurement