recipe = token+
token = measurement / word / whitespace
word = #'[^\s]+'
measurement = quantity <whitespace>* unit
whitespace = #'\s+'
quantity = mixed | integer | decimal | fraction
mixed = integer <whitespace> fraction
integer = #'\d+'
decimal = #'\d+\.\d+'
fraction = #'\d+\/\d+'
unit = oz | cl | tablespoon | cup
oz = 'ozs' / 'oz' / 'ounces' / 'ounce'
cl = 'cls' / 'cl' / 'centiliters' / 'centiliter'
tablespoon = 'tbsps' / 'tbsp' / 'tablespoons' / 'tablespoon'
cup = 'cups' / 'cup'
