recipe = token+
token = measurement / word / whitespace
word = #'[^\s]+'
measurement = quantity <whitespace>* unit <#'(?!\w)'>
whitespace = #'\s+'
quantity = mixed | integer | decimal | fraction
mixed = integer <whitespace> fraction
integer = #'\d+'
decimal = #'\d+\.\d+'
fraction = #'\d+\/\d+'
unit = oz | cup | tablespoon | teaspoon
oz = #'ozs?' | #'ounces?' | #'fl ozs?' | #'fluid ounces?'
cup = #'cups?'
tablespoon = #'tbsps?' | #'tablespoons?'
teaspoon = #'tsps?' | #'teaspoons?'
