unit = oz | cup | tablespoon | teaspoon
oz = #'(?i)ozs?' | #'(?i)ounces?' | #'(?i)fl ozs?' | #'(?i)floz' | #'(?i)fluid ounces?'
cup = #'(?i)cups?'
tablespoon = #'(?i)tbsps?' | #'(?i)tablespoons?'
teaspoon = #'(?i)tsps?' | #'(?i)teaspoons?'
