unit = floz | cup | tablespoon | teaspoon | gallon | pint | quart | mile | yard | foot | inch |
pound | oz

(* Volume *)
floz = #'(?i)fl\.? ozs?' | #'(?i)fl\.?ozs?' | #'(?i)fluid ounces?'
cup = #'(?i)cups?' | #'(?i)cp'
tablespoon = #'(?i)tbsps?' | #'(?i)tablespoons?'
teaspoon = #'(?i)tsps?' | #'(?i)teaspoons?'
gallon = #'(?i)gallons?' | #'(?i)gals?'
pint = #'(?i)pints?' | #'(?i)pts?'
quart = #'(?i)quarts?' | #'(?i)qts?'

(* Distance *)
mile = #'(?i)miles?' | #'(?i)mi'
yard = #'(?i)yards?' | #'(?i)yd'
foot = #'(?i)foot' | #'(?i)feet' | #'(?i)ft' | '\''
inch = #'(?i)inch(es)?' | #'(?i)in' | '\"'

(* Weight *)
pound = #'(?i)pounds?' | #'(?i)lbs?'
oz = #'(?i)ozs?' | #'(?i)ounces?' | #'(?i)ounces?\(dry\)' | #'(?i)oz\(dry\)?'
